### ISSUE TITLE
have QC setup as part of default configuration for all runs?

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#109]
What is the overhead for doing the things needed for the quality control comparisons ("-s qc" to generate and position necessary files) for all simulations?   I've done a bunch of simulations without it, and now it would be nice to go back and check the qc output without having to re-run the simulations.

**Comment by eclare108213** [comment]
A big piece of the "necessary files" is 5 years of daily output.  We wouldn't generate that for every run, certainly, but if we were generating it anyhow...  maybe a different way to ask this question is this:  is there a relatively painless way to retroactively set up what's needed for the qc tests, if we happen to have the output already?

**Comment by mattdturner** [comment]
If I understand correctly, you are asking about how easy it might be to use the QC script on runs that already generated 5 years worth of daily output?  The script should already be setup to properly run with those inputs.

The problem would be that the QC tests (as far as I understand them) require instantaneous output, not averaged output.  So, while the script should run with the inputs from any 5 years of daily output, the tests might not be 100% appropriate due to the fact that the default namelist has ``hist_avg = .true.``

**Comment by eclare108213** [comment]
These are runs that I created for Andrew to analyze, and we kept the aisnap and hisnap fields, which are always instantaneous even when everything else is averaged.  I tried running the script on them and I get this error:

> $ cice.t-test.py /net/scratch3/eclare/CICE_RUNS/gx1.20yr/history /net/scratch3/eclare/CICE_RUNS/gx1.nonBFB_tmass
> INFO:__main__:Number of files: 0
> Traceback (most recent call last):
>   File "cice.t-test.py", line 441, in <module>
>     data_a, data_b, data_d, num_files, path_a, fname = read_data(args.base_dir,args.test_dir)
>   File "cice.t-test.py", line 56, in read_data
>     nfid = nc.Dataset("{}/{}".format(path_a,files_a[0]),'r')

The script works when I use directories that were generated with -s qc.

**Comment by mattdturner** [comment]
The script looks for files in the ``history/`` directories that start with ``iceh_inst.``.  Since the script says that there are 0 files, I would assume that the files do not start with ``iceh_inst.``.  I'd be happy to change the script to look for a filename that might work more universally, I just didn't want the script to also try to read data from files that do not provide the instantaneous output.

**Comment by eclare108213** [comment]
I see.  We'll need to think about this.  Options could be to allow hisnap to be read from any file name, or either hi or hisnap from iceh_inst.
